# fly.toml app configuration file generated for chaton-stash-com on 2024-11-27T16:51:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chaton-stash-com'
primary_region = 'cdg'
console_command = '/rails/bin/rails console'

[build]
  RAILS_ENV = "production"
  PORT = "8080"

[http_service]
  processes = ["app"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[processes]
  app = "bundle exec thrust ./bin/rails server"
  solidq = "bundle exec rake solid_queue:start"

[mounts]
  source="data"
  destination="/data"

